version: "0.0.1"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    attach: false
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - VERSION=docker
      - PLEX_CLAIM=claim-token #PUT YOUR PLEX CLAIM TOKEN HERE
    volumes:
      - /mnt/pzro/plex/config:/config
      - /mnt/pzro/:/mnt/pzro
    restart: unless-stopped
  
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest    
    container_name: zurg
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./zurg/plex_update.sh:/app/plex_update.sh
      - ./zurg/config.yml:/app/config.yml
      - /mnt/pzro/zurg/data:/app/data

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      TZ: America/Bogota
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/pzro/zurg:/data:rshared 
      - ./zurg/rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"
   
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Bogota
      - PORT=5055
      - PUID=1000
      - PGID=1000
    ports:
      - 5055:5055
    volumes:
      - /mnt/pzro/overseerr/data:/app/config
    restart: unless-stopped